import img0 from "../assets/img0.png";
import img1 from "../assets/img1.png";
import img2 from "../assets/img2.png";
import img3 from "../assets/img3.png";
import img4 from "../assets/img4.png";
import img5 from "../assets/img5.png";

export const bookingData = [
  {
    name: "Bluenose",
    status: "Pending",
    date: "10/01/24 15/01/24".split(' '),
    suite: true,
    img: img0,
    id: 1,
    place: 'Room 35',
    room: false,
  },
  {
    name: "Pennywise",
    status: "Done",
    date: "10/01/24 15/01/24".split(' '),
    suite: false,
    img: img1,
    id: 2,
    place: 'Room 11',
    room: true,
  },
  {
    name: "Khalil",
    status: "Cancel",
    date: "10/01/24 15/01/24".split(' '),
    suite: false,
    img: img2,
    id: 3,
    place: 'Suite 3',
    room: true,
  },
  {
    name: "Flotsam",
    status: "Unverified",
    date: 'No date available',
    suite: true,
    img: img3,
    id: 4,
    place: 'Suite 12',
    room: false,
  },
  {
    name: "Ronaldo",
    status: "Done",
    date: "10/01/24 15/01/24".split(' '),
    suite: true,
    img: img5,
    id: 5,
    place: 'Suite 7',
    room: false,
  },
  {
    name: "Bluenose",
    status: "Pending",
    date: "10/01/24 15/01/24".split(' '),
    suite: true,
    img: img0,
    id: 6,
    place: 'Room 35',
    room: false,
  },
  {
    name: "Pennywise",
    status: "Done",
    date: "10/01/24 15/01/24".split(' '),
    suite: false,
    img: img1,
    id: 7,
    place: 'Room 11',
    room: true,
  },
  {
    name: "Khalil",
    status: "Cancel",
    date: "10/01/24 15/01/24".split(' '),
    suite: false,
    img: img2,
    id: 8,
    place: 'Suite 3',
    room: true,
  },
  {
    name: "Flotsam",
    status: "Unverified",
    date: 'No date available',
    suite: true,
    img: img3,
    id: 9,
    place: 'Suite 12',
    room: false,
  },
  {
    name: "Gojo",
    status: "Cancel",
    date: "10/01/24 15/01/24".split(' '),
    suite: false,
    img: img4,
    id: 10,
    place: 'Room 23',
    room: true,
  },
  {
    name: "Messi",
    status: "Done",
    date: "10/01/24 15/01/24".split(' '),
    suite: true,
    img: img5,
    id: 11,
    place: 'Suite 7',
    room: false,
  },
];
