export const roomsData = [
  {
    place: "Room 1",
    bed: "Single bed",
    id : 1,
    person: "1 Person",
    available: true,
  },
  {
    place: "Room 2",
    bed: "Double bed",
    id : 2,
    person: "2 Person",
    available: true,
  },
  {
    place: "Room 3",
    bed: "Two Double Bed",
    id : 3,
    person: "3 Person",
    available: true,
  },
  {
    place: "Room 4",
    bed: "Double+Single Bed",
    id : 4,
    person: "4 Person",
    available: true,
  },
  {
    place: "Room 5",
    bed: "Single bed",
    id : 5,
    person: "2 Person",
    available: true,
  },
  {
    place: "Room 6",
    bed: "Double bed",
    id : 6,
    person: "3 Person",
    available: true,
  },
  {
    place: "Suite 1",
    bed: "Two Double Bed",
    id : 7,
    person: "4 Person",
    available: true,
  },
  {
    place: "Suite 2",
    bed: "Double+Single Bed",
    id : 8,
    person: "1 Person",
    available: true,
  },
  {
    place: "Suite 3",
    bed: "Single bed",
    id : 9,
    person: "3 Person",
    available: true,
  },
  {
    place: "Suite 4",
    bed: "Double bed",
    id : 10,
    person: "2 Person",
    available: true,
  },
  {
    place: "Suite 5",
    bed: "Two Double Bed",
    id : 11,
    person: "4 Person",
    available: true,
  },
];
